# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Scala.gitlab-ci.yml

# Official OpenJDK Java image. Look for the different tagged releases at
# https://hub.docker.com/_/openjdk/ . A Java image is not required
# but an image with a JVM speeds up the build a bit.
image: registry.gitlab.com/mhammons/slinc:latest

stages:
  - build
  - test
  - pages

compile: 
  stage: build
  cache:
    - key: mill
      paths: 
        - .cache/*
    - key: $CI_PIPELINE_ID
      paths:
        - out/*
  script:    
    - XDG_CACHE_HOME=$CI_BUILDS_DIR/$CI_PROJECT_PATH/.cache mill -D user.home=$CI_BUILDS_DIR/$CI_PROJECT_PATH/ clean
    - XDG_CACHE_HOME=$CI_BUILDS_DIR/$CI_PROJECT_PATH/.cache mill -D user.home=$CI_BUILDS_DIR/$CI_PROJECT_PATH/ cstd.compile


test:
  stage: test
  cache:
    - key: mill
      paths: 
        - .cache/*
    - key: $CI_PIPELINE_ID
      paths:
        - out/*

  script:
    - XDG_CACHE_HOME=$CI_BUILDS_DIR/$CI_PROJECT_PATH/.cache mill -D user.home=$CI_BUILDS_DIR/$CI_PROJECT_PATH/ _.test

pages: 
  stage: pages
  cache:
    - key: mill
      paths: 
        - .cache/*
    - key: $CI_PIPELINE_ID
      paths:
        - out/*
  needs: [test]
  script: 
    - XDG_CACHE_HOME=$CI_BUILDS_DIR/$CI_PROJECT_PATH/.cache mill -D user.home=$CI_BUILDS_DIR/$CI_PROJECT_PATH/ slinc.docJar
    - cp -rv out/slinc/docJar.dest/javadoc .
    - mv javadoc public
  artifacts:
    paths:
      - public
  when: manual
